CREATE TABLE url (
                     id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                     short_code   VARCHAR(255)                NOT NULL,
                     original_url VARCHAR(2048)               NOT NULL,
                     custom_alias BOOLEAN                     NOT NULL,
                     created_at   TIMESTAMP(6) WITH TIME ZONE,
                     expires_at   TIMESTAMP(6) WITH TIME ZONE,
                     click_count  INTEGER                     NOT NULL,
                     CONSTRAINT uk_url_short_code UNIQUE (short_code)
);